### ISSUE TITLE
Using SMB and SMB2J Disassemblies

### ISSUE THREAD

**Issue by htv04** [Ersanio/SMAS-Disassembly#13]
I was comparing the code between the SMB disassembly and the SMAS SMB disassembly and found that a lot of the code was very similar. The comprehensive disassemblies of SMB and SMB2J can come in very handy for documenting functions.

SMB: https://www.romhacking.net/documents/344/
SMB2J: https://www.romhacking.net/documents/653/

**Comment by Ersanio** [comment]
I added the links to README.md - could be very useful!
