### ISSUE TITLE
Assembly and Disassembly redundancy

### ISSUE THREAD

**Issue by bonimy** [Ersanio/SMAS-Disassembly#2]
# Issue
So presently, we have to folders the source code, [Assembly](https://github.com/Ersanio/SMAS-Disassembly/tree/master/Assembly) and [Disassembly](https://github.com/Ersanio/SMAS-Disassembly/tree/master/Disassembly). This feels redundant as they host the same code, but in different formats:

**Assembly format**:
```
Reset:
CODE_008000:        SEI                       ; Set interput flag
CODE_008001:        STZ $4200                 ; Disable NMI, IRQ, and joypad read
CODE_008004:        STZ $420C                 ; HDMA Disabled
CODE_008007:        STZ $420B                 ; DMA Disabled
```

**Disassembly format**:
```
Reset:
CODE_008000:        78            SEI                       ; Set interput flag
CODE_008001:        9C 00 42      STZ $4200                 ; Disable NMI, IRQ, and joypad read
CODE_008004:        9C 0C 42      STZ $420C                 ; HDMA Disabled
CODE_008007:        9C 0B 42      STZ $420B                 ; DMA Disabled
```

# Resolution
I was thinking we merge both of these formats in a way that's assemblable.

**Merged format**:
```
Reset:
CODE_008000:   SEI               ; CODE_008000:   78          ; Set interput flag
               STZ $4200         ; CODE_008001:   9C 00 42    ; Disable NMI, IRQ, and joypad read
               STZ $420C         ; CODE_008004:   9C 0C 42    ; HDMA Disabled
               STZ $420B         ; CODE_008007:   9C 0B 42    ; DMA Disabled
```

**Ersanio's suggested format**:
```
Reset:
CODE_008000:   SEI               ; 008000:   78          ; Set interput flag
               STZ $4200         ; 008001:   9C 00 42    ; Disable NMI, IRQ, and joypad read
               STZ $420C         ; 008004:   9C 0C 42    ; HDMA Disabled
               STZ $420B         ; 008007:   9C 0B 42    ; DMA Disabled
```

The idea is to have a format that can still be assembled, while keeping all of the important information the disassembly provides (the address of each instruction and the byte codes of the instruction). For the assembly, we also strip all of the unused labels to help clean up our code and speed up assembly time. But by having the labels saved in the comments, we can easily know where we are and insert the new labels in the whitespace if it turns out to be needed by any indirect pointers.

**Comment by Ersanio** [comment]
Maybe we can make the merged format even less verbose by replacing CODE_XXYYYY: with simply $XXYYYY: or even without the $

**Comment by bonimy** [comment]
Hmm that's a good point. Edited post to reflect format.
